import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';

import styles from '../styles/Layout.module.css';
import utilStyles from '../styles/utils.module.css';

const Layout = ({ children, home }) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                {home ? (
                    <> <Image
                        priority
                        src="/img/1.jpg"
                        className={utilStyles.borderCircle}
                        height={144} width={144}
                        alt='Imagen' />
                        <h1 className={utilStyles.heading2Xl}>Hector Wong</h1> </>
                ) : (
                    <>
                        <Link href="/">
                            <a>
                                <Image
                                    riority src="/img/1.jpg"
                                    className={utilStyles.borderCircle}
                                    height={108} width={108}
                                    alt='Hola' />
                            </a>
                        </Link>
                        <h2 className={utilStyles.headingLg}>
                            <Link href="/">
                                <a className={utilStyles.colorInherit}>
                                    Hector Wong</a>
                            </Link>
                        </h2>
                    </>
                )} </header>

            <nav className={styles.navbar} >
                <Link href={'/Blog'}>
                    <a>About me |</a>
                </Link>
                <Link href={'/About'}>
                    <a> Blog </a>
                </Link>
            </nav>
            <main>
                {children}
            </main>
            <footer>
                Pie de pagina
            </footer>
        </div>
    )
};

export default Layout;
